# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(503, 366)
        self.selections = QtWidgets.QComboBox(Form)
        self.selections.setGeometry(QtCore.QRect(270, 30, 221, 22))
        self.selections.setObjectName("selections")
        self.selections.addItem("")
        self.selections.addItem("")
        self.selections.addItem("")
        self.selections.addItem("")
        self.selections.addItem("")
        self.label_selections = QtWidgets.QLabel(Form)
        self.label_selections.setGeometry(QtCore.QRect(270, 10, 61, 16))
        self.label_selections.setObjectName("label_selections")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 231, 69))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_name = QtWidgets.QLabel(self.layoutWidget)
        self.label_name.setObjectName("label_name")
        self.verticalLayout.addWidget(self.label_name)
        self.lineedit_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineedit_name.setObjectName("lineedit_name")
        self.verticalLayout.addWidget(self.lineedit_name)
        self.button_name = QtWidgets.QPushButton(self.layoutWidget)
        self.button_name.setObjectName("button_name")
        self.verticalLayout.addWidget(self.button_name)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 100, 231, 241))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_description = QtWidgets.QLabel(self.layoutWidget1)
        self.label_description.setObjectName("label_description")
        self.verticalLayout_2.addWidget(self.label_description)
        self.textbrowser_description = QtWidgets.QTextBrowser(self.layoutWidget1)
        self.textbrowser_description.setObjectName("textbrowser_description")
        self.verticalLayout_2.addWidget(self.textbrowser_description)
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(270, 100, 221, 241))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.question = QtWidgets.QLabel(self.layoutWidget2)
        self.question.setObjectName("question")
        self.verticalLayout_3.addWidget(self.question)
        self.plaintextedit_question = QtWidgets.QPlainTextEdit(self.layoutWidget2)
        self.plaintextedit_question.setObjectName("plaintextedit_question")
        self.verticalLayout_3.addWidget(self.plaintextedit_question)
        self.button_question = QtWidgets.QPushButton(self.layoutWidget2)
        self.button_question.setObjectName("button_question")
        self.verticalLayout_3.addWidget(self.button_question)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.selections.setItemText(0, _translate("Form", "First"))
        self.selections.setItemText(1, _translate("Form", "Second"))
        self.selections.setItemText(2, _translate("Form", "Third"))
        self.selections.setItemText(3, _translate("Form", "Forth"))
        self.selections.setItemText(4, _translate("Form", "Fifth"))
        self.label_selections.setText(_translate("Form", "Class"))
        self.label_name.setText(_translate("Form", "Name"))
        self.button_name.setText(_translate("Form", "Submit"))
        self.label_description.setText(_translate("Form", "Description"))
        self.question.setText(_translate("Form", "Wanna add something?"))
        self.button_question.setText(_translate("Form", "Submit"))
