# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connect.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(390, 224)
        self.pushButton_connect = QtWidgets.QPushButton(Form)
        self.pushButton_connect.setGeometry(QtCore.QRect(280, 180, 75, 23))
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.label_prompt = QtWidgets.QLabel(Form)
        self.label_prompt.setGeometry(QtCore.QRect(70, 20, 251, 16))
        self.label_prompt.setObjectName("label_prompt")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(32, 62, 321, 101))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_ip = QtWidgets.QLabel(self.widget)
        self.label_ip.setObjectName("label_ip")
        self.verticalLayout.addWidget(self.label_ip)
        self.label_username = QtWidgets.QLabel(self.widget)
        self.label_username.setObjectName("label_username")
        self.verticalLayout.addWidget(self.label_username)
        self.label_password = QtWidgets.QLabel(self.widget)
        self.label_password.setObjectName("label_password")
        self.verticalLayout.addWidget(self.label_password)
        self.label_database = QtWidgets.QLabel(self.widget)
        self.label_database.setObjectName("label_database")
        self.verticalLayout.addWidget(self.label_database)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_ip = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.verticalLayout_2.addWidget(self.lineEdit_ip)
        self.lineEdit_username = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.verticalLayout_2.addWidget(self.lineEdit_username)
        self.lineEdit_password = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout_2.addWidget(self.lineEdit_password)
        self.lineEdit_database = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_database.setObjectName("lineEdit_database")
        self.verticalLayout_2.addWidget(self.lineEdit_database)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_connect.setText(_translate("Form", "Connect"))
        self.label_prompt.setText(_translate("Form", "Please enter the information to connect to the database"))
        self.label_ip.setText(_translate("Form", "IP"))
        self.label_username.setText(_translate("Form", "Username"))
        self.label_password.setText(_translate("Form", "Password"))
        self.label_database.setText(_translate("Form", "Database"))

        # fill in the information by default
        self.lineEdit_ip.setText(_translate("Form", "combination_of_digits"))
        self.lineEdit_username.setText(_translate("Form", "my_username"))
        self.lineEdit_password.setText(_translate("Form", "my_password"))
        self.lineEdit_database.setText(_translate("Form", "my_database"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
